IS_DEBUG = True

VMCONF_CONTAINER_NAME = 'eu.gcr.io/infrary-main/vmconf'
VMCONF_OCTO_CONF_KEY = 'octo_conf'
VMCONF_PRIVATE_KEY_KEY = 'private_key'
VMCONF_VMCONF_KEY = 'vm_conf'
VMCONF_SERVER_ID_KEY = "server_id"
VMCONF_SERVER_PROVIDER_KEY = "server_provider"
VMCONF_OCTO_TOKEN_KEY = "octo_token"
VMCONF_SERVER_HOSTNAME_KEY = "server_hostname"
VMCONF_COMMAND_LIST_KEY = "cmd_list"
VMCONF_IS_MASTER_KEY = "is_master"
VMCONF_SELF_DESTRUCT_KEY = "self_destruct"
VMCONF_MASTERCONF_KEY = "master_conf"
VMCONF_COMPOSE_STACKS_KEY = "compose_stacks"

MASTERCONF_SECRET_KEY = 'secret'
MASTERCONF_PASSWORD_KEY = 'password'
MASTERCONF_USER_KEY = 'user'
MASTERCONF_HOST_KEY = 'host'

ACCESS_TOKEN_KEY = 'token'
STATUS_DB_KEY = "status"
MASTERCONF_KEY = 'master_conf'
SELF_DESTRUCT_KEY = 'self_destruct'
IS_MASTER_KEY = 'is_master'
VM_CONFIGURATION_DB_KEY = "vm_configuration"
ID_KEY = 'id'
PROVIDER_KEY = 'provider'
IP_KEY = 'ip'
TEMP_SSH_KEY_KEY = 'temp_ssh_key'
SSH_KEY_FINGERPRINT_KEY = 'ssh_fgpt'

OCTO_TOKEN_KEY = 'OCTO_TOKEN'
OCTO_CONFIGURED_SERVER_SUBMIT_PATH_KEY = 'OCTO_CONFIGURED_SERVER_SUBMIT_PATH'
OCTO_SERVER_STATUS_SUBMIT_PATH_KEY = 'OCTO_SERVER_STATUS_SUBMIT_PATH'
OCTO_SERVER_LOG_SUBMIT_PATH_KEY = 'OCTO_SERVER_LOG_SUBMIT_PATH'
OCTO_MESSAGE_SUBMIT_PATH_KEY = 'OCTO_MESSAGE_SUBMIT_PATH'
OCTO_SERVER_SUBMIT_PATH_KEY = 'OCTO_SERVER_SUBMIT_PATH'
OCTO_URL_KEY = 'OCTO_URL'
